# Generated by Django 5.1.1 on 2024-09-27 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_agency_name_alter_user_agency_owner_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='agency_name',
            field=models.CharField(blank=True, max_length=254, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='agency_owner_name',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='agency_owner_phone',
            field=models.CharField(blank=True, max_length=11, null=True, unique=True),
        ),
    ]
