# Generated by Django 5.1.1 on 2024-10-02 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_otpcode'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgencyUserModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agency_name', models.CharField(max_length=254, unique=True)),
                ('agency_owner_name', models.CharField(max_length=254)),
                ('agency_owner_phone', models.CharField(max_length=11, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='NormalUserModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=254)),
                ('phone', models.CharField(max_length=11, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('is_active', models.BooleanField(default=False)),
            ],
        ),
    ]
