# Generated by Django 5.1.1 on 2024-10-02 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_agencyusermodel_normalusermodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='agencyusermodel',
            name='is_agency',
            field=models.BooleanField(default=False),
        ),
    ]
