# Generated by Django 5.1.1 on 2024-10-02 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_agencyusermodel_is_agency'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AgencyUserModel',
        ),
        migrations.DeleteModel(
            name='NormalUserModel',
        ),
    ]
