# Generated by Django 5.1.1 on 2024-10-03 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_user_agency_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='agency_email',
            field=models.EmailField(blank=True, default='None', max_length=254, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='agency_name',
            field=models.CharField(blank=True, default='None', max_length=254, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='agency_owner_name',
            field=models.CharField(blank=True, default='None', max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='agency_owner_phone',
            field=models.CharField(blank=True, default='None', max_length=11, null=True, unique=True),
        ),
    ]
