# Generated by Django 5.1.1 on 2024-10-05 09:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_alter_user_agency_email_alter_user_agency_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254, verbose_name='Hotel Name')),
                ('address', models.TextField(verbose_name='آدرس هتل')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات تکمیلی')),
                ('star', models.IntegerField(choices=[(3, '3 Star'), (4, '4 Star'), (5, '5 Star')], default=3)),
                ('type', models.CharField(choices=[('normal', 'Normal Hotel'), ('suite', 'Suite Hotel')], default='normal', max_length=254)),
                ('hotel_image', models.ImageField(upload_to='hotels/')),
                ('check_in_time', models.TimeField()),
                ('check_out_time', models.TimeField()),
                ('breakfast', models.BooleanField(default=False, verbose_name='وعده صبحانه')),
                ('wifi', models.BooleanField(default=False, verbose_name='وای فای')),
                ('swimming_pool', models.BooleanField(default=False, verbose_name='استخر شنا')),
                ('refrigerator', models.BooleanField(default=False, verbose_name='یخچال')),
                ('tea_maker', models.BooleanField(default=False, verbose_name='چای ساز')),
                ('tv', models.BooleanField(default=False, verbose_name='تلویزیون')),
                ('air_condition', models.BooleanField(default=False, verbose_name='کولرگازی')),
                ('parking', models.BooleanField(default=False, verbose_name='پارکینگ اخنصاصی')),
                ('turkish_hamam', models.BooleanField(default=False, verbose_name='حمام ترکی')),
                ('pet', models.BooleanField(default=False, verbose_name='ورود حیوان خانگی')),
                ('room_service', models.BooleanField(default=False, verbose_name='سرویس نظافت اتاق')),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_type', models.CharField(choices=[('single', 'Single Room'), ('double', 'Double Room'), ('triple', 'Triple Room'), ('quad', 'Quad Room'), ('five', 'Five Bed Room'), ('six', 'Six Bed Room'), ('seven', 'Seven Bed Room'), ('eight', 'Eight Bed Room'), ('nine', 'Nine Bed Room'), ('ten', 'Ten Bed Room')], max_length=254)),
                ('price_per_night', models.IntegerField()),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(upload_to='rooms/')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Room', to='accounts.hotel')),
            ],
        ),
    ]
