# Generated by Django 5.1.1 on 2024-10-05 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='check_in_time',
            field=models.TimeField(verbose_name='ساعت تحویل اتاق'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='check_out_time',
            field=models.TimeField(verbose_name='ساعت تخلیه اتاق'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='name',
            field=models.CharField(max_length=254, verbose_name='نام هتل'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='star',
            field=models.IntegerField(choices=[(3, '3 Star'), (4, '4 Star'), (5, '5 Star')], default=3, verbose_name='ستاره هتل'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='type',
            field=models.CharField(choices=[('normal', 'Normal Hotel'), ('suite', 'Suite Hotel')], default='normal', max_length=254, verbose_name='نوع هتل'),
        ),
    ]
