# Generated by Django 5.1.1 on 2024-10-05 16:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_hotel_check_in_time_alter_hotel_check_out_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotel',
            name='hotel_image',
        ),
        migrations.CreateModel(
            name='HotelImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='hotels/images/', verbose_name='عکس های هتل')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='HotelImages', to='home.hotel')),
            ],
        ),
    ]
