# Generated by Django 5.1.1 on 2024-10-06 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_room_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='type',
            field=models.CharField(choices=[('hotel', 'هتل'), ('suite', 'سوئیت')], default='normal', max_length=254, verbose_name='نوع هتل'),
        ),
    ]
