# Generated by Django 5.1.1 on 2024-10-06 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_hotel_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='hotels/main_images/'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='type',
            field=models.CharField(choices=[('hotel', 'هتل'), ('suite', 'سوئیت')], default='هتل', max_length=254, verbose_name='نوع هتل'),
        ),
    ]
