# Generated by Django 5.1.1 on 2024-10-06 21:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_hotel_image_alter_hotel_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hotel',
            old_name='image',
            new_name='main_image',
        ),
    ]
