# Generated by Django 5.1.1 on 2024-10-06 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_rename_image_hotel_main_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='type',
            field=models.CharField(choices=[('هتل', 'هتل'), ('سوئیت', 'سوئیت')], default='هتل', max_length=254, verbose_name='نوع هتل'),
        ),
    ]
