# Generated by Django 5.1.1 on 2024-10-11 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_alter_room_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='room_type',
            field=models.CharField(choices=[('اتاق تک تخته', 'Single Room'), ('اتاق دو تخته', 'Double Room'), ('اتاق سه تخته', 'Triple Room'), ('اتاق ۴ تخته', 'Quad Room'), ('اتاق ۵ تخته', 'Five Bed Room'), ('اتاق ۶ تخته', 'Six Bed Room'), ('اتاق ۷ تخته', 'Seven Bed Room'), ('اتاق ۸ تخته', 'Eight Bed Room'), ('اتاق ۹ تخته', 'Nine Bed Room'), ('اتاق ۱۰ تخته', 'Ten Bed Room')], max_length=254),
        ),
    ]
