# Generated by Django 5.1.1 on 2024-10-11 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_alter_room_room_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='latitude',
            field=models.FloatField(default=0.0, verbose_name='عرض جغرافیایی'),
        ),
        migrations.AddField(
            model_name='hotel',
            name='longitude',
            field=models.FloatField(default=0.0, verbose_name='طول جغرافیایی'),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_type',
            field=models.CharField(choices=[('اتاق ۱ تخته', 'Single Room'), ('اتاق ۲ تخته', 'Double Room'), ('اتاق ۳ تخته', 'Triple Room'), ('اتاق ۴ تخته', 'Quad Room'), ('اتاق ۵ تخته', 'Five Bed Room'), ('اتاق ۶ تخته', 'Six Bed Room'), ('اتاق ۷ تخته', 'Seven Bed Room'), ('اتاق ۸ تخته', 'Eight Bed Room'), ('اتاق ۹ تخته', 'Nine Bed Room'), ('اتاق ۱۰ تخته', 'Ten Bed Room')], max_length=254),
        ),
    ]
