# Generated by Django 5.1.1 on 2024-10-11 21:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_hotel_latitude_hotel_longitude_alter_room_room_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotel',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='longitude',
        ),
    ]
