# Generated by Django 5.1.1 on 2024-10-13 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_remove_hotel_latitude_remove_hotel_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='offers_hotel',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='هتل پیشنهادی'),
        ),
        migrations.AddField(
            model_name='room',
            name='offers_room',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='اتاق پیشنهادی'),
        ),
    ]
