# Generated by Django 5.1.1 on 2024-10-25 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_comment_hotel_room'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='hotel_room',
        ),
    ]
