# Generated by Django 5.1.1 on 2024-10-25 19:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_remove_comment_hotel_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='hotel_room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='room_comment', to='home.room'),
        ),
    ]
