# Generated by Django 5.1.1 on 2024-11-09 14:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_booking_natid'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={'ordering': ['-checkin']},
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='adults',
            new_name='adult',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='sumprice',
        ),
        migrations.AlterField(
            model_name='booking',
            name='tax',
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=100)),
                ('passport_number', models.CharField(max_length=11)),
                ('birthdate', models.DateField()),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.booking')),
            ],
        ),
    ]
