# Generated by Django 5.1.1 on 2024-11-12 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_booking_options_rename_adults_booking_adult_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='passfullname',
            new_name='fullname',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='emailaddr',
        ),
        migrations.AlterField(
            model_name='guest',
            name='passport_number',
            field=models.CharField(max_length=9),
        ),
    ]
