# Generated by Django 5.1.1 on 2024-11-12 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_rename_passfullname_booking_fullname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='paymethod',
            field=models.CharField(blank=True, choices=[('کارت به کارت', 'کارت به کارت'), ('نقدی', 'نقدی')], max_length=13, verbose_name='روش پرداخت'),
        ),
    ]
