# Generated by Django 5.1.1 on 2024-11-12 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_booking_is_paid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='natid',
            field=models.IntegerField(max_length=10, unique=True),
        ),
    ]
