# Generated by Django 5.1.1 on 2024-11-12 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_alter_booking_natid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='natid',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
