# Generated by Django 5.1.1 on 2024-11-12 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_alter_booking_natid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='natid',
            field=models.PositiveIntegerField(unique=True),
        ),
    ]
