# Generated by Django 5.1.1 on 2024-11-12 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_alter_booking_natid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='natid',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='phonenum',
        ),
    ]
