# Generated by Django 5.1.1 on 2024-11-14 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_booking_mustpay_booking_totalprice_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Guest',
            new_name='Passenger',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='user',
        ),
        migrations.AddField(
            model_name='booking',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='توضیحات مشتری'),
        ),
    ]
